/*This file autogenerated, do not edit*/

struct addressBookDynamicPage {
  int error;
  int page;
  void *handle;
  int (*count)();
  struct Customers *(*read)();
  struct Customers *data;
};

struct addressBookDynamicPage loadPage(int page);
int unload_page(struct addressBookDynamicPage page);
