/**
 * @file delete_executor.c
 * @brief Executes DELETE operations
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <errno.h>
#include <dirent.h>
#include <time.h>
#include "delete_executor.h"
#include "../schema/metadata.h"
#include "../schema/type_system.h"
#include "../loader/page_manager.h"
#include "../loader/record_access.h"
#include "../kernel/kernel_generator.h"
#include "../kernel/kernel_compiler.h"
#include "../kernel/kernel_loader.h"
#include "../pages/page_generator.h"
#include "../pages/page_splitter.h"
#include "../query/query_executor.h"

/**
 * @brief Create delete result
 */
static DeleteResult* create_delete_result(void) {
    DeleteResult* result = malloc(sizeof(DeleteResult));
    result->rows_affected = 0;
    result->success = false;
    result->error_message = NULL;
    return result;
}

/**
 * @brief Set error in result
 */
static void set_delete_error(DeleteResult* result, const char* format, ...) {
    result->success = false;
    
    va_list args;
    va_start(args, format);
    
    char buffer[1024];
    vsnprintf(buffer, sizeof(buffer), format, args);
    
    result->error_message = strdup(buffer);
    
    va_end(args);
}

/**
 * @brief Generate delete kernel
 */
static GeneratedKernel* generate_delete_kernel(const DeleteStatement* stmt, 
                                              const TableSchema* schema,
                                              const char* base_dir) {
    // Create a synthetic SELECT statement to use existing kernel generator
    SelectStatement select_stmt;
    select_stmt.from_table = malloc(sizeof(TableRef));
    select_stmt.from_table->table_name = strdup(stmt->table_name);
    select_stmt.from_table->alias = NULL;
    
    // Use WHERE clause from DELETE
    select_stmt.where_clause = stmt->where_clause;
    
    // Set up as SELECT * for full row access
    select_stmt.select_list.has_star = true;
    select_stmt.select_list.expressions = NULL;
    select_stmt.select_list.count = 0;
    
    // Generate kernel
    GeneratedKernel* kernel = generate_select_kernel(&select_stmt, schema, base_dir);
    
    // Clean up
    free(select_stmt.from_table->table_name);
    free(select_stmt.from_table);
    
    return kernel;
}

/**
 * @brief Physically delete records from a data file
 */
static int delete_records_from_file(const char* data_path, void** records, int record_count,
                                   void** matches, int match_count) {
    // Open the file for reading
    FILE* read_file = fopen(data_path, "r");
    if (!read_file) {
        fprintf(stderr, "Failed to open data file for reading: %s\n", data_path);
        return -1;
    }
    
    // Read the entire file into memory
    char** lines = NULL;
    int line_count = 0;
    char buffer[4096];
    
    while (fgets(buffer, sizeof(buffer), read_file)) {
        lines = realloc(lines, (line_count + 1) * sizeof(char*));
        lines[line_count] = strdup(buffer);
        line_count++;
    }
    
    fclose(read_file);
    
    // Create a bitmap to mark records for deletion
    bool* to_delete = calloc(record_count, sizeof(bool));
    
    // Mark records for deletion based on matches
    for (int i = 0; i < match_count; i++) {
        for (int j = 0; j < record_count; j++) {
            if (matches[i] == records[j]) {
                to_delete[j] = true;
                break;
            }
        }
    }
    
    // Find lines that represent records (those containing struct initializers)
    // Each record is a line ending with "},\n"
    int* record_lines = malloc(record_count * sizeof(int));
    int found_records = 0;
    
    for (int i = 0; i < line_count && found_records < record_count; i++) {
        // Check if this line represents a record
        size_t len = strlen(lines[i]);
        if (len >= 3 && lines[i][len-3] == '}' && lines[i][len-2] == ',' && lines[i][len-1] == '\n') {
            record_lines[found_records++] = i;
        }
    }
    
    // Open file for writing
    FILE* write_file = fopen(data_path, "w");
    if (!write_file) {
        fprintf(stderr, "Failed to open data file for writing: %s\n", data_path);
        
        // Clean up
        for (int i = 0; i < line_count; i++) {
            free(lines[i]);
        }
        free(lines);
        free(to_delete);
        free(record_lines);
        
        return -1;
    }
    
    // Write header
    fprintf(write_file, "/*This file autogenerated, do not edit manually*/\n");
    
    // Write lines, skipping deleted records
    int deleted = 0;
    int line_idx = 0;
    
    while (line_idx < line_count) {
        // Check if this is a record line to delete
        bool skip = false;
        
        if (found_records > 0) {
            for (int i = 0; i < found_records; i++) {
                if (line_idx == record_lines[i] && to_delete[i]) {
                    skip = true;
                    deleted++;
                    break;
                }
            }
        }
        
        if (!skip) {
            fputs(lines[line_idx], write_file);
        }
        
        line_idx++;
    }
    
    fclose(write_file);
    
    // Clean up
    for (int i = 0; i < line_count; i++) {
        free(lines[i]);
    }
    free(lines);
    free(to_delete);
    free(record_lines);
    
    return deleted;
}

/**
 * @brief Execute a DELETE statement
 */
DeleteResult* execute_delete(const DeleteStatement* stmt, const char* base_dir) {
    DeleteResult* result = create_delete_result();
    
    if (!stmt || !base_dir) {
        set_delete_error(result, "Invalid parameters");
        return result;
    }
    
    // Load table schema using the shared function
    TableSchema* schema = load_table_schema(stmt->table_name, base_dir);
    if (!schema) {
        set_delete_error(result, "Table '%s' not found", stmt->table_name);
        return result;
    }
    
    // Validate statement
    if (!validate_delete_statement(stmt, schema)) {
        set_delete_error(result, "DELETE statement validation failed");
        free_table_schema(schema);
        return result;
    }
    
    // Generate kernel for finding matching records
    GeneratedKernel* kernel = NULL;
    LoadedKernel loaded_kernel;
    bool kernel_loaded = false;
    
    if (stmt->where_clause) {
        kernel = generate_delete_kernel(stmt, schema, base_dir);
        if (!kernel) {
            set_delete_error(result, "Failed to generate delete kernel");
            free_table_schema(schema);
            return result;
        }
        
        // Compile kernel
        char kernel_path[2048];
        if (compile_kernel(kernel, base_dir, stmt->table_name, -1, 
                          kernel_path, sizeof(kernel_path)) != 0) {
            set_delete_error(result, "Failed to compile delete kernel");
            free_generated_kernel(kernel);
            free_table_schema(schema);
            return result;
        }
        
        // Load kernel
        if (load_kernel(kernel_path, kernel->kernel_name, stmt->table_name, -1, 
                       &loaded_kernel) != 0) {
            set_delete_error(result, "Failed to load delete kernel");
            free_generated_kernel(kernel);
            free_table_schema(schema);
            return result;
        }
        kernel_loaded = true;
    }
    
    // Track affected pages
    bool* affected_pages = NULL;
    int page_count = 0;
    
    // Count pages
    char compiled_dir[2048];
    snprintf(compiled_dir, sizeof(compiled_dir), "%s/compiled", base_dir);
    DIR* dir = opendir(compiled_dir);
    if (dir) {
        struct dirent* entry;
        while ((entry = readdir(dir)) != NULL) {
            if (strstr(entry->d_name, stmt->table_name) && 
                strstr(entry->d_name, ".so")) {
                page_count++;
            }
        }
        closedir(dir);
    }
    
    affected_pages = calloc(page_count, sizeof(bool));
    
    // Process each page
    int total_deleted = 0;
    for (int page_num = 0; page_num < page_count; page_num++) {
        LoadedPage page;
        
        if (load_page(base_dir, stmt->table_name, page_num, &page) != 0) {
            continue;
        }
        
        int page_records;
        if (get_page_count(&page, &page_records) != 0) {
            unload_page(&page);
            continue;
        }
        
        void** records = malloc(page_records * sizeof(void*));
        for (int i = 0; i < page_records; i++) {
            read_record(&page, i, &records[i]);
        }
        
        int delete_count = 0;
        
        // Get data file path
        char data_path[2048];
        snprintf(data_path, sizeof(data_path), "%s/tables/%s/data/%sData.%d.dat.h", 
                 base_dir, stmt->table_name, stmt->table_name, page_num);
        
        if (stmt->where_clause && kernel_loaded) {
            // Use kernel to find matching records
            // Calculate the actual record size
            size_t record_size = calculate_record_size((const struct TableSchema*)schema);

            // Allocate space for full record structures
            void* matches = malloc(page_records * record_size);

            if (!matches) {
                fprintf(stderr, "Failed to allocate matches buffer\n");
                unload_page(&page);
                free(records);
                continue;
            }
            
            delete_count = execute_kernel(&loaded_kernel, records, page_records,
                                         matches, page_records);
            
            // Now physically delete the records
            if (delete_count > 0) {
                void** match_ptrs = malloc(delete_count * sizeof(void*));
                for (int i = 0; i < delete_count; i++) {
                    match_ptrs[i] = (char*)matches + (i * record_size);
                }
                
                // Delete the matching records from the data file
                int deleted = delete_records_from_file(data_path, records, page_records,
                                                      match_ptrs, delete_count);
                
                if (deleted > 0) {
                    affected_pages[page_num] = true;
                    total_deleted += deleted;
                }
                
                free(match_ptrs);
            }
            
            free(matches);
        } else {
            // No WHERE clause - delete all records
            // Just write an empty data file with only the header
            FILE* file = fopen(data_path, "w");
            if (file) {
                fprintf(file, "/*This file autogenerated, do not edit manually*/\n");
                fclose(file);
                
                affected_pages[page_num] = true;
                total_deleted += page_records;
            }
        }
        
        free(records);
        unload_page(&page);
    }
    
    // Recompile affected pages
    for (int i = 0; i < page_count; i++) {
        if (affected_pages[i]) {
            recompile_data_page(schema, base_dir, i);
        }
    }
    
    // Update metadata
    if (total_deleted > 0) {
        TableMetadata metadata;
        if (load_table_metadata(stmt->table_name, base_dir, &metadata) == 0) {
            metadata.record_count -= total_deleted;
            time(&metadata.modified_at);
            update_table_metadata(&metadata, base_dir);
        }
    }
    
    result->rows_affected = total_deleted;
    result->success = true;
    
    // Cleanup
    free(affected_pages);
    if (kernel_loaded) {
        unload_kernel(&loaded_kernel);
    }
    if (kernel) {
        free_generated_kernel(kernel);
    }
    free_table_schema(schema);
    
    return result;
}

/**
 * @brief Free delete result
 */
void free_delete_result(DeleteResult* result) {
    if (result) {
        free(result->error_message);
        free(result);
    }
}
