/*This file autogenerated, do not edit manually*/
{1, "John Doe", "john@example.com", 35, true},
{2, "Jane Smith", "jane@example.com", 28, true},
{3, "Bob Johnson", "bob@example.com", 42, false},
{4, "Alice Brown", "alice@example.com", 31, true},
{5, "Charlie Davis", "charlie@example.com", 45, true},
