/*This file autogenerated, do not edit*/
unsigned long long addressBookPageCount = 2;

struct addressBookDynamicPage {
  int error;
  int page;
  void *handle;
  int (*count)();
  struct Customers *(*read)();
  struct Customers *data;
};
