/*This file autogenerated, do not edit*/
struct Customers CustomersData_1[] =  {
/*BEGIN Customers DATA*/
#include "../data/addressBookData.1.dat.h"  /*We can include JUST the data portion!*/
/*END Customers DATA*/
, NULL //ending with NULL gives me a way to stop when I don't have the count. like /0 in char *

};
